/**
 * Purge all ValidatedMapping entries flagged by the latest AI audit.
 * Reads the purge-list JSON generated by the audit script.
 */
import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PURGE_FILE = path.join(__dirname, '..', 'logs',
    'ai-mapping-audit-2026-04-23T21-06-16-155Z-purge-list.json');

async function main() {
    const purgeList: Array<{ id: string; rawIngredient: string; foodName: string; reason: string }> =
        JSON.parse(fs.readFileSync(PURGE_FILE, 'utf-8'));

    console.log(`📋 Purge list loaded: ${purgeList.length} entries`);
    console.log('');
    purgeList.forEach(e => {
        console.log(`  🗑  "${e.rawIngredient}" → "${e.foodName}"`);
        console.log(`       ${e.reason.slice(0, 120)}`);
    });
    console.log('');

    const ids = purgeList.map(e => e.id);
    const result = await prisma.validatedMapping.deleteMany({ where: { id: { in: ids } } });
    console.log(`✅ Purged: ${result.count} entries`);

    const remaining = await prisma.validatedMapping.count();
    console.log(`   ValidatedMapping remaining: ${remaining}`);

    await prisma.$disconnect();
}

main().catch(e => { console.error(e); prisma.$disconnect(); process.exit(1); });
