/**
 * Clear Old Pipeline Cache Tables
 * 
 * Run this script before using the new simplified pipeline to ensure
 * a clean slate. Old cache may contain:
 * - Incorrect modifier mappings (fat-free → reduced-fat)
 * - Bloated FatSecretFoodCache from old candidate gathering
 * - AI normalization that stripped modifiers
 * 
 * Usage: npx tsx scripts/clear-old-pipeline-cache.ts
 */

import 'dotenv/config';
import { prisma } from '../src/lib/db';

async function clearOldPipelineCache() {
    console.log('🧹 Clearing old pipeline cache tables...\n');

    // 1. FatSecretFoodCache - old pipeline cached too many entries
    const cacheCount = await prisma.fatSecretFoodCache.deleteMany({});
    console.log(`✓ FatSecretFoodCache: ${cacheCount.count} entries deleted`);

    // 2. ValidatedMapping - old mappings may have wrong modifiers
    const mappingCount = await prisma.validatedMapping.deleteMany({});
    console.log(`✓ ValidatedMapping: ${mappingCount.count} entries deleted`);

    // 3. AiNormalizeCache - old AI normalization stripped modifiers
    const normalizeCount = await prisma.aiNormalizeCache.deleteMany({});
    console.log(`✓ AiNormalizeCache: ${normalizeCount.count} entries deleted`);

    // 4. LearnedSynonym - will be regenerated by new pipeline
    const synonymCount = await prisma.learnedSynonym.deleteMany({});
    console.log(`✓ LearnedSynonym: ${synonymCount.count} entries deleted`);

    // 5. MappingValidationFailure - historical failures from old pipeline
    const failureCount = await prisma.mappingValidationFailure.deleteMany({});
    console.log(`✓ MappingValidationFailure: ${failureCount.count} entries deleted`);

    console.log('\n✅ All cache tables cleared! Ready for new pipeline.');
    console.log('\nNext steps:');
    console.log('  1. Run pilot import: ENABLE_MAPPING_ANALYSIS=true npx tsx scripts/pilot-batch-import.ts --limit 10');
    console.log('  2. Review mapping analysis in logs/ folder');
}

clearOldPipelineCache()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
