#!/usr/bin/env bash
#
# refresh-off-from-parquet.sh — quarterly full refresh of the OffFood table
# from Open Food Facts' Parquet export.
#
# WHY THIS EXISTS: the weekly delta cron (ingest-off-delta.ts) consumes OFF's
# JSONL delta files, which inherit the JSONL export's missing-`nutriments` bug
# and also can't represent deletions. Measured 2026-07-30 on a real delta file:
# 2,937 of 2,939 US/EN products (99.9%) carry NO `nutriments` object at all, and
# a 12-day catch-up run scanned 61,796 lines and would have upserted 0. So the
# delta lane is a near-no-op for nutrition and THIS script is the only thing
# that actually refreshes the corpus. Do not read a green weekly delta run as
# "the corpus is fresh".
#
#   download Parquet (~7GB) -> off-parquet-to-jsonl.sh (slim ~330MB JSONL)
#   -> snapshot FoodMapping + derived OffServing -> ingest-off.ts --fresh
#   -> restore-off-pointers.ts -> restore-off-servings.ts
#   -> regenerate corruptReason + duplicateOfBarcode -> sync-typesense.ts
#
# CURATION SURVIVAL (added 2026-07-31, after the 2026-07-30 refresh destroyed
# three separate populations and nobody noticed for a day). The question that
# matters is NOT "what does the truncate touch" — enumerating that failed twice
# — but "which of these does no upstream source regenerate?" Each answer gets a
# different mechanism, and all three are wired into this script:
#
#   packageQuantity        -> REGENERATED BY THE INGEST. Fixed 2026-07-31 by
#                             adding product_quantity/quantity to
#                             off-parquet-to-jsonl.sh's SELECT. Needs nothing here.
#   corruptReason,         -> REGENERATED AFTER the ingest by re-running the
#   duplicateOfBarcode        detectors/dedupe. Deliberately NOT replayed from a
#                             snapshot: they are derivations of the panel, and a
#                             refresh can bring a CORRECTED panel — replaying a
#                             stale mark would suppress a row OFF has since fixed.
#                             corruptReason has TWO producers, both required:
#                             detect-corrupt-panel.ts (sibling-median, 6,905
#                             marks) and detect-corrupt-nutrition.ts (per-field
#                             physics, 22,087). Naming one restores a quarter of
#                             the column while looking like it worked.
#                             NOT covered: the hand-authored marks, which no
#                             re-derivation can reproduce. Open — see
#                             backend_integration_guide.md.
#   derived OffServing     -> SNAPSHOT + REPLAY. These ('ai', 'sibling_borrow')
#                             are the only population that is neither ingested
#                             nor derivable: re-running the estimator RE-ROLLS
#                             them. That is the n-svk-05 mechanism.
#
# The snapshot/restore pair either side of the ingest is not optional bookkeeping:
# `--fresh` NULLs FoodMapping.offBarcode on ~81% of the cache to satisfy the FK
# before deleting OffFood. Barcodes are OFF's stable primary key, so those
# pointers are recoverable — but only from a snapshot taken BEFORE the truncate.
# Embeddings are the other loss and are NOT restored here: re-run embed_foods.py
# afterwards (measured 2026-07-30: ~327 rows/sec on the box's CPU, so ~55min for
# the full corpus — a GPU is not required).
#
# See the mobile repo's sync-docs/archive/handoff_food_data_quality_audit.md
# ("TRUE root cause" section) for the full investigation.
#
# Safe to run manually at any time, ON THE BOX:
#   ~/Recipe-App/scripts/refresh-off-from-parquet.sh
#
# --preflight-only runs every safety check and exits without downloading or
# writing anything. The destructive path takes ~hours and cannot be rehearsed,
# so this is the only way to know the guards work before the quarterly timer
# fires; the timer's first real run is still a human decision.

set -euo pipefail

PREFLIGHT_ONLY=0
for a in "$@"; do
  case "$a" in
    --preflight-only) PREFLIGHT_ONLY=1 ;;
    *) echo "unknown argument: $a" >&2; exit 64 ;;
  esac
done

REPO="${REPO:-$HOME/Recipe-App}"
WORKDIR="${WORKDIR:-$HOME/Downloads}"
PARQUET="$WORKDIR/off-food.parquet"
SLIM_JSONL="$WORKDIR/off-products-parquet.jsonl.gz"
PARQUET_URL='https://huggingface.co/datasets/openfoodfacts/product-database/resolve/main/food.parquet?download=true'

export PATH="$HOME/.local/bin:$HOME/.nvm/versions/node/v24.18.0/bin:$PATH"

cd "$REPO"
export DATABASE_URL="${DATABASE_URL:-$(grep -E '^DATABASE_URL=' .env | head -1 | cut -d= -f2- | tr -d '"')}"
export OFF_COUNTRIES="${OFF_COUNTRIES:-united-states,canada,united-kingdom,ireland,australia,new-zealand}"

# PREFLIGHT — every one of these must hold BEFORE the destructive `--fresh`
# ingest truncates OffFood. This block exists because the script previously
# ended in `meilisearch-sync.ts`, a file deleted when the provider became
# Typesense: under `set -e` that aborted AFTER the truncate-and-reingest, so a
# quarterly run would have left the corpus rebuilt and the search index stale,
# and reported failure only in a log nobody reads. Fail before touching data.
echo "[$(date -Is)] Preflight..."
PREFLIGHT_FAIL=0
# HOST GUARD — this must run ON the box. Every dev machine's .env points
# DATABASE_URL at the box's Postgres (192.168.1.133:5432), so running this from
# a laptop truncates the LIVE OffFood table. That is not hypothetical: on
# 2026-07-30 a run started from the Mac got as far as the finished slim JSONL,
# two steps from the truncate, before a timeout ended it. Override only if you
# have read this and mean it: OFF_REFRESH_ALLOW_REMOTE=1.
if [ "$(hostname)" != "DHL32-Opt-5060" ] && [ "${OFF_REFRESH_ALLOW_REMOTE:-0}" != "1" ]; then
  echo "  ❌ not running on the box (hostname=$(hostname)) — this truncates the LIVE OffFood table."
  echo "     Run it on the box:  ssh owner@192.168.1.133 '~/Recipe-App/scripts/refresh-off-from-parquet.sh'"
  PREFLIGHT_FAIL=1
fi
command -v duckdb >/dev/null 2>&1 || { echo "  ❌ duckdb CLI not on PATH (needed by off-parquet-to-jsonl.sh)"; PREFLIGHT_FAIL=1; }
[ -x "$REPO/scripts/off-parquet-to-jsonl.sh" ] || { echo "  ❌ scripts/off-parquet-to-jsonl.sh missing or not executable"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/ingest-off.ts" ]           || { echo "  ❌ scripts/ingest-off.ts missing"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/sync-typesense.ts" ]       || { echo "  ❌ scripts/sync-typesense.ts missing"; PREFLIGHT_FAIL=1; }
# The snapshot/restore pair is checked HERE because a missing restore path
# discovered after the truncate is a missing restore path, not an error message.
[ -f "$REPO/scripts/eval/_snap_foodmapping.ts" ]     || { echo "  ❌ scripts/eval/_snap_foodmapping.ts missing — no pre-truncate snapshot is possible"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/eval/restore-off-pointers.ts" ]  || { echo "  ❌ scripts/eval/restore-off-pointers.ts missing — the cache pointers would be unrecoverable"; PREFLIGHT_FAIL=1; }
# CURATION — everything below is a column or row that NO upstream source
# regenerates, so a missing script here is a permanent data loss discovered
# after the truncate. The 2026-07-30 refresh destroyed all three populations
# because nothing checked for them; that is what these lines are.
[ -f "$REPO/scripts/eval/_snap_off_servings.ts" ]    || { echo "  ❌ scripts/eval/_snap_off_servings.ts missing — derived ai/sibling_borrow servings would be unrecoverable"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/eval/restore-off-servings.ts" ]  || { echo "  ❌ scripts/eval/restore-off-servings.ts missing — the derived-serving snapshot could not be replayed"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/eval/detect-corrupt-panel.ts" ]  || { echo "  ❌ scripts/eval/detect-corrupt-panel.ts missing — corruptReason could not be regenerated"; PREFLIGHT_FAIL=1; }
# There are TWO corrupt detectors, and corruptReason is regenerated only if BOTH
# run. The 2026-08-01 marks were 22,087 rows from this one and 6,905 from the
# panel scan; a preflight naming one detector passes a run that restores a
# quarter of the column.
[ -f "$REPO/scripts/eval/detect-corrupt-nutrition.ts" ] || { echo "  ❌ scripts/eval/detect-corrupt-nutrition.ts missing — the per-field physics marks could not be regenerated"; PREFLIGHT_FAIL=1; }
# Only the PHYSICS directions of the nutrition scan are applied unattended. The
# same scan also emits judgement rules — panel-inflated-serving,
# sodium-implausible, sodium-sibling-outlier — which must never be auto-applied:
# panel-inflated-serving assumes servingGrams is one eating occasion, false for
# a large package, so it fires on 8000500273296, whose stored panel is Ferrero
# Rocher's CORRECT one. Held rows stay in the scan report for a human to audit.
NUTRITION_PHYSICS='kcal-impossible,macro-sum-impossible,fiber-impossible,sugars-impossible,sodium-impossible'
# Validated HERE, against the detector's own source, because the alternative is
# discovering a typo'd direction after the truncate — and mark-corrupt-off.ts's
# fail-closed exit would then abort a run that has already rebuilt the corpus.
# The doc-check claim off-refresh-nutrition-allowlist-not-stale runs the same
# script, so the two cannot disagree.
if [ -x "$REPO/scripts/check-nutrition-allowlist.sh" ]; then
  # Merged so a refusal (exit 2, printed to stderr) is reported rather than read
  # as an empty result; the count is the last line the script writes.
  ALLOWLIST_OUT="$("$REPO/scripts/check-nutrition-allowlist.sh" 2>&1 || echo REFUSED)"
  [ "$(printf '%s\n' "$ALLOWLIST_OUT" | tail -1)" = "0" ] \
    || { echo "  ❌ NUTRITION_PHYSICS did not validate: $ALLOWLIST_OUT"; PREFLIGHT_FAIL=1; }
else
  echo "  ❌ scripts/check-nutrition-allowlist.sh missing or not executable — NUTRITION_PHYSICS could not be validated"; PREFLIGHT_FAIL=1
fi
[ -f "$REPO/scripts/mark-corrupt-off.ts" ]           || { echo "  ❌ scripts/mark-corrupt-off.ts missing — corruptReason could not be regenerated"; PREFLIGHT_FAIL=1; }
[ -f "$REPO/scripts/dedupe-off-mark.ts" ]            || { echo "  ❌ scripts/dedupe-off-mark.ts missing — duplicateOfBarcode could not be regenerated"; PREFLIGHT_FAIL=1; }
# THIRD detector, and the only one this script cannot act on — see its stage
# below for why it reports rather than repairs.
[ -f "$REPO/scripts/eval/detect-panel-scale-divided.ts" ] || { echo "  ❌ scripts/eval/detect-panel-scale-divided.ts missing — the divided-panel population would be silently re-corrupted"; PREFLIGHT_FAIL=1; }
[ -x "$REPO/node_modules/.bin/ts-node" ]       || { echo "  ❌ node_modules/.bin/ts-node missing — run npm ci"; PREFLIGHT_FAIL=1; }
[ -n "${DATABASE_URL:-}" ]                     || { echo "  ❌ DATABASE_URL empty"; PREFLIGHT_FAIL=1; }
# ~7GB parquet + ~330MB slim JSONL + headroom.
AVAIL_KB=$(df -Pk "$WORKDIR" 2>/dev/null | awk 'NR==2{print $4}')
[ "${AVAIL_KB:-0}" -ge 15000000 ] || { echo "  ❌ <15GB free on $WORKDIR (have ${AVAIL_KB:-0}KB)"; PREFLIGHT_FAIL=1; }
if [ "$PREFLIGHT_FAIL" -ne 0 ]; then
  echo "[$(date -Is)] ❌ Preflight failed — refusing to run. NOTHING was changed."
  exit 2
fi
echo "[$(date -Is)] Preflight OK."

# BLAST RADIUS — print what `ingest-off.ts --fresh` will destroy, from the live
# DB, every time. Measured 2026-07-30 the first time anyone looked: this is not
# "refresh the corpus", it is a rebuild that also drops ~1.07M pgvector
# embeddings and NULLs the offBarcode on ~81% of the FoodMapping cache.
echo "[$(date -Is)] Blast radius (live):"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only -e '
const { PrismaClient } = require("@prisma/client");
(async () => {
  const p = new PrismaClient();
  const [r] = await p.$queryRawUnsafe(`SELECT
    (SELECT count(*) FROM "OffFood")                                     AS offfood,
    (SELECT count(*) FROM "OffFood" WHERE embedding IS NOT NULL)         AS embedded,
    (SELECT count(*) FROM "OffServing")                                  AS servings,
    -- Dollar-quoted deliberately. This whole node -e program sits inside a
    -- single-quoted shell string, so a single-quoted SQL literal here ends the
    -- shell string early and Postgres then reads the value as an identifier
    -- (fails with: column openfoodfacts does not exist).
    (SELECT count(*) FROM "OffServing" WHERE source <> $$openfoodfacts$$)  AS derived_servings,
    (SELECT count(*) FROM "OffFood" WHERE "corruptReason" IS NOT NULL)   AS corrupt_marks,
    (SELECT count(*) FROM "OffFood" WHERE "duplicateOfBarcode" IS NOT NULL) AS dupe_marks,
    (SELECT count(*) FROM "OffFood" WHERE "packageQuantity" IS NOT NULL) AS pkg_qty,
    -- The divided-panel repair has NO column of its own, so it cannot be
    -- counted directly. This is its canary: the flagship pair carries a
    -- size-invariant density when repaired (173.12 vs 172.78, ratio 1.00) and
    -- the same per-serving figure at both sizes when divided (ratio ~2).
    (SELECT coalesce(round(max(k)/nullif(min(k),0),2)::text,$$NONE$$) FROM (
       SELECT ("nutrientsPer100g"->>$$calories$$)::numeric AS k FROM "OffFood"
       WHERE barcode IN ($$9039713284064100139$$,$$21021796406979553492283$$)) t) AS panel_canary,
    (SELECT count(*) FROM "FoodMapping" WHERE "offBarcode" IS NOT NULL)  AS mapped`);
  console.log(`  OffFood rows deleted        : ${r.offfood}`);
  console.log(`  ...pgvector embeddings lost : ${r.embedded}  (NOT restored here — re-run scripts/embed-off-cpu.ts; ~55min on this box CPU, measured 2026-07-30)`);
  console.log(`  OffServing rows deleted     : ${r.servings}`);
  console.log(`  ...of which DERIVED         : ${r.derived_servings}  (ai / sibling_borrow — SNAPSHOTTED and replayed after the ingest)`);
  console.log(`  FoodMapping.offBarcode NULLed: ${r.mapped}  (RESTORED automatically after the ingest, minus products OFF delisted)`);
  console.log(`  corruptReason marks wiped   : ${r.corrupt_marks}  (REGENERATED after the ingest by the detect->mark chain)`);
  console.log(`  duplicateOfBarcode wiped    : ${r.dupe_marks}  (REGENERATED after the ingest by dedupe-off-mark.ts)`);
  console.log(`  packageQuantity rows        : ${r.pkg_qty}  (REGENERATED by the ingest itself since 2026-07-31)`);
  // No apostrophes in this string: the whole node -e program sits inside a
  // single-quoted shell string, so one would end it early — the same trap the
  // SQL above dollar-quotes around.
  console.log(`  divided-panel repair        : canary ratio ${r.panel_canary}  (1.00 = repaired, ~2 = already lost;` +
    ` NOT regenerated and NOT replayable here — the refresh re-imports the divided numbers straight from OFF, and` +
    ` the repair needs an approved plan and a DEV MACHINE. 3,166 rows as of 2026-08-08.)`);
  await p.$disconnect();
})();' || { echo "  ❌ could not read the blast radius — refusing to guess"; exit 2; }

if [ "$PREFLIGHT_ONLY" -eq 1 ]; then
  echo "[$(date -Is)] --preflight-only: all guards pass. Nothing downloaded, nothing written."
  exit 0
fi

# ACKNOWLEDGEMENT GATE — the numbers above are why this cannot be an unattended
# job. A timer fires with a bare environment, so a scheduled run lands here and
# stops; a human who has read the blast radius and has a re-embedding plan sets
# the variable. This is deliberate: losing 1M embeddings quietly at 02:00 on a
# Tuesday is exactly the kind of failure this codebase keeps writing gates for.
if [ "${OFF_REFRESH_I_ACCEPT_DATA_LOSS:-0}" != "1" ]; then
  echo "[$(date -Is)] ⛔ Refusing: this rebuilds the corpus and drops the embeddings above."
  echo "     Nothing was downloaded or written."
  echo "     Recoverable automatically by this script:"
  echo "       - FoodMapping.offBarcode — snapshotted before the truncate and restored after."
  echo "       - derived OffServing ('ai'/'sibling_borrow') — snapshotted and replayed after."
  echo "       - corruptReason + duplicateOfBarcode — re-derived after the ingest, before the"
  echo "         Typesense sync, so the index never holds the bad rows."
  echo "       - packageQuantity — written by the ingest itself since 2026-07-31."
  echo "     NOT recovered here, plan for it first:"
  echo "       - the pgvector embeddings. Re-run scripts/embed_foods.py afterwards"
  echo "         (~327 rows/sec on this box's CPU, measured 2026-07-30 — no GPU needed)."
  echo "         Until it finishes, keyword search is unaffected but semantic recall is degraded."
  echo "       - cache rows whose product OFF has delisted; the restore prints them as a worklist."
  echo "     Then re-run with OFF_REFRESH_I_ACCEPT_DATA_LOSS=1."
  exit 3
fi
echo "[$(date -Is)] OFF_REFRESH_I_ACCEPT_DATA_LOSS=1 — proceeding with the destructive refresh."

# A 7GB pull over a home line WILL be interrupted. The first real run
# (2026-07-30) died at 4.7GB on `curl: (92) HTTP/2 stream not closed cleanly`,
# and plain --retry restarts from byte zero, which never converges. Force
# HTTP/1.1 (the stream resets are an HTTP/2-multiplexing artifact), resume the
# partial with -C -, and retry on transport errors too, not just HTTP codes.
echo "[$(date -Is)] Downloading Parquet export (resumable)..."
curl -fL --http1.1 -C - --retry 8 --retry-all-errors --retry-delay 10 \
  --connect-timeout 30 -sS -o "$PARQUET.tmp" "$PARQUET_URL"
mv "$PARQUET.tmp" "$PARQUET"
echo "[$(date -Is)] Downloaded: $(du -h "$PARQUET" | cut -f1)"

echo "[$(date -Is)] Converting Parquet -> slim JSONL..."
"$REPO/scripts/off-parquet-to-jsonl.sh" "$PARQUET" "$SLIM_JSONL"

# SNAPSHOT — Role B (restore anchor): taken as late as possible, immediately
# before the truncate, so live traffic between here and the ingest is minimal.
# Deliberately AFTER the slow download/convert, which can take hours.
STAMP="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
SNAP="$WORKDIR/FoodMapping-pre-refresh-$STAMP.json"
echo "[$(date -Is)] Snapshotting FoodMapping -> $SNAP"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/_snap_foodmapping.ts "$SNAP"

# The derived servings ('ai', 'sibling_borrow') are the one population that
# neither the ingest nor a re-scan can reproduce — re-running the estimator
# re-ROLLS them. Snapshot beside the pointers, replay after the ingest.
SNAP_SERV="$WORKDIR/OffServing-derived-pre-refresh-$STAMP.json"
echo "[$(date -Is)] Snapshotting derived OffServing rows -> $SNAP_SERV"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/_snap_off_servings.ts "$SNAP_SERV"

echo "[$(date -Is)] Running --fresh ingest..."
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  scripts/ingest-off.ts "$SLIM_JSONL" --fresh

# RESTORE — exit 3 means "completed, with residue an operator must reconcile"
# (products OFF delisted). That is an expected outcome of a real refresh, not a
# failure, so it must not abort the run under `set -e`; exit 2 is a refusal and
# MUST stop everything. Anything else is unknown and also stops.
echo "[$(date -Is)] Restoring FoodMapping.offBarcode pointers..."
set +e
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/restore-off-pointers.ts "$SNAP" --execute
RESTORE_RC=$?
set -e
case "$RESTORE_RC" in
  0) echo "[$(date -Is)] Pointers fully restored." ;;
  3) echo "[$(date -Is)] ⚠️  Pointers restored with residue (see the worklist above). Snapshot kept: $SNAP" ;;
  *) echo "[$(date -Is)] ❌ Pointer restore FAILED (rc=$RESTORE_RC). The cache is missing its OFF pointers."
     echo "     The snapshot is intact — replay by hand:"
     echo "     scripts/eval/restore-off-pointers.ts $SNAP --execute"
     exit "$RESTORE_RC" ;;
esac

# REPLAY the derived servings. Same exit-code contract as the pointer restore:
# 3 is "completed, with residue an operator must read" (delisted products, or a
# description a live row already holds), which is an expected outcome.
echo "[$(date -Is)] Replaying derived OffServing rows..."
set +e
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/restore-off-servings.ts "$SNAP_SERV" --execute
SERV_RC=$?
set -e
case "$SERV_RC" in
  0) echo "[$(date -Is)] Derived servings fully replayed." ;;
  3) echo "[$(date -Is)] ⚠️  Derived servings replayed with residue (see worklist above). Snapshot kept: $SNAP_SERV" ;;
  *) echo "[$(date -Is)] ❌ Derived-serving replay FAILED (rc=$SERV_RC)."
     echo "     The snapshot is intact — replay by hand:"
     echo "     scripts/eval/restore-off-servings.ts $SNAP_SERV --execute"
     exit "$SERV_RC" ;;
esac

# REGENERATE the curation marks. These are NOT replayed from a snapshot on
# purpose: they are derivations of the panel, and the refresh may have brought a
# corrected panel with it — replaying a stale mark would suppress a row OFF has
# since fixed. Re-deriving is both fresher and cheaper than reasoning about it.
#
# This runs BEFORE the Typesense sync deliberately: sync-typesense.ts already
# filters `corruptReason IS NULL AND duplicateOfBarcode IS NULL`, so marking
# first means the index never contains the bad rows and no purge step is needed.
# The 2026-07-30 refresh skipped this chain entirely and shipped 100,513
# unmarked rows into the index.
echo "[$(date -Is)] Regenerating corruptReason marks..."
# The scan names its own report with a timestamp, so it is written into an
# EMPTY per-run directory and the only file in it is the one we just made —
# globbing a shared results/ dir would pick up an older scan on a re-run.
CORRUPT_DIR="$WORKDIR/corrupt-scan-$STAMP"
mkdir -p "$CORRUPT_DIR"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/detect-corrupt-panel.ts --out-dir "$CORRUPT_DIR"
CORRUPT_SCAN="$(ls -1 "$CORRUPT_DIR"/corrupt-panel-scan-*.json 2>/dev/null | head -1)"
[ -n "$CORRUPT_SCAN" ] || { echo "  ❌ the corrupt scan produced no report — refusing to continue with an unmarked corpus"; exit 2; }
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/mark-corrupt-off.ts --file "$CORRUPT_SCAN" --apply

# SECOND detector: per-FIELD physical impossibilities (kcal > 905/100g, macro
# sum > 105 g/100g, ...). Separate from the panel scan above, which only catches
# whole panels stored at per-serving scale via same-name sibling medians.
# $NUTRITION_PHYSICS and why it is an allowlist: see the preflight.
echo "[$(date -Is)] Regenerating per-field nutrition marks (physics directions only)..."
NUTRITION_DIR="$WORKDIR/nutrition-scan-$STAMP"
mkdir -p "$NUTRITION_DIR"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/detect-corrupt-nutrition.ts --out-dir "$NUTRITION_DIR"
NUTRITION_SCAN="$(ls -1 "$NUTRITION_DIR"/corrupt-nutrition-scan-*.json 2>/dev/null | head -1)"
[ -n "$NUTRITION_SCAN" ] || { echo "  ❌ the nutrition scan produced no report — refusing to continue with an unmarked corpus"; exit 2; }
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/mark-corrupt-off.ts --file "$NUTRITION_SCAN" \
  --only-reasons "$NUTRITION_PHYSICS" --apply

echo "[$(date -Is)] Regenerating duplicateOfBarcode marks..."
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/dedupe-off-mark.ts

# THIRD detector: the divided-panel population — chain OFF imports whose stored
# per-100g panel is the per-serving panel divided by the serving size, so a
# Jersey Mike's Giant and Regular both bill an identical ~173 kcal.
#
# THIS ONE REPORTS AND DOES NOT REPAIR, and that is deliberate rather than a gap:
#   - repair-panel-scale-divided.ts --execute REFUSES without an approved --plan
#     and an explicit --tier. The plan IS the approval record; auto-generating
#     one inside this run would defeat the gate on a write that multiplies
#     panels by up to 10.6x.
#   - it also verifies its snapshot over ssh, and the snapshot itself is taken
#     over ssh, so neither half can run box-side at all.
# So the correct behaviour here is to make the loss LOUD. It has been silent
# twice: the population was repaired on 2026-07-27, destroyed on 2026-07-30, and
# the loss was not noticed for nine days.
echo "[$(date -Is)] Scanning for divided panels (report only — the repair is a separate, approved run)..."
PANEL_SCAN="$WORKDIR/panel-scale-divided-$STAMP.json"
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  -r tsconfig-paths/register scripts/eval/detect-panel-scale-divided.ts --arm synthetic --out "$PANEL_SCAN"
[ -f "$PANEL_SCAN" ] || { echo "  ❌ the divided-panel scan produced no report — refusing to finish blind"; exit 2; }
# READ flaggedRows FROM THE REPORT, NEVER THE EXIT CODE. scanExitCode() returns
# 2 only when the scan saw NOTHING (scanned == 0 or baseFilterPassed == 0) and
# returns 0 with the entire population flagged — so `detect-... && echo clean`
# is fail-open, and this is the one place that mistake would be invisible.
PANEL_FLAGGED="$(node -e 'const fs=require("fs");try{const r=JSON.parse(fs.readFileSync(process.argv[1],"utf8"));process.stdout.write(typeof r.flaggedRows==="number"?String(r.flaggedRows):"ERR")}catch(e){process.stdout.write("ERR")}' "$PANEL_SCAN")"
[ "$PANEL_FLAGGED" != "ERR" ] || { echo "  ❌ could not read flaggedRows from $PANEL_SCAN — refusing to finish blind"; exit 2; }
echo "[$(date -Is)]   divided-panel rows flagged: $PANEL_FLAGGED  (report: $PANEL_SCAN)"

echo "[$(date -Is)] Re-syncing Typesense..."
node_modules/.bin/ts-node --project tsconfig.scripts.json --transpile-only \
  scripts/sync-typesense.ts

# The 7GB parquet is only needed transiently; the slim JSONL is kept as the
# record of what was ingested (and for cheap re-runs without a re-download).
rm -f "$PARQUET"

# The snapshot is deliberately NOT deleted: it is the only record of what the
# pointers were, and the restore's residue worklist is only actionable against it.
echo "[$(date -Is)] ✅ Refresh complete."
if [ "$PANEL_FLAGGED" -gt 0 ] 2>/dev/null; then
  echo "[$(date -Is)] ⚠️  DIVIDED-PANEL REPAIR IS LOST: $PANEL_FLAGGED rows are billing a"
  echo "     per-serving panel at per-100g scale again. This refresh re-imported OFF's own"
  echo "     divided numbers; nothing in this script can put them back."
  echo "     It must be repaired FROM A DEV MACHINE (both the snapshot and its verification"
  echo "     go over ssh, so neither runs box-side), and it needs Diego's approved plan:"
  echo "       0a. scripts/eval/detect-panel-scale-divided.ts   (already run: $PANEL_SCAN)"
  echo "       0b. scripts/eval/repair-panel-scale-divided.ts --out plan.json     # dry run"
  echo "       0c. ...--execute --plan <approved> --snapshot-manifest <m> --tier 1|2|all"
  echo "     THEN a FULL sync-typesense.ts again, or search keeps billing the old panels"
  echo "     off the Typesense hit. Canary: Jersey Mike's #44 Regular vs Giant should agree"
  echo "     on kcal/100g to well under 1%; ~2x disagreement means still divided."
fi
echo "[$(date -Is)] NEXT, two steps — semantic recall is degraded until BOTH are done"
echo "     (keyword search is unaffected; the Typesense vector field is optional):"
echo "       1. scripts/embed-off-cpu.ts   — every OffFood row now has a NULL embedding."
echo "          Use this, NOT embed_foods.py: the box has no torch/sentence_transformers."
echo "       2. scripts/sync-typesense.ts  — AGAIN. searchOffSemantic() reads vectors from"
echo "          Typesense, not pgvector, and the sync above ran before the embeddings existed."
echo "     Snapshot retained at: $SNAP"
