name: Nightly Similar Build

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call similar endpoint
        run: |
          set -euo pipefail
          curl -sS -X POST \
            -H "X-Cron-Secret: $CRON_SECRET" \
            "$VERCEL_URL/api/admin/cron/similar"
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}


