name: PR Size

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIZES: >
            XS=0..19
            S=20..99
            M=100..399
            L=400..799
            XL=800..1599
            XXL=1600..
